### ISSUE TITLE
[Spike] Scrape FCC Code editor

### ISSUE THREAD

**Issue by apprentamentors** [user512/teacher_dashboard#3]
- [ ] Scraper can return code editor HTML string 
- [ ] Experiment parsing scraped string and display it using https://codemirror.net/
- [ ] Look for iframe solution if spike doesn't workout.

**Comment by user512** [comment]
After doing some investigations, I think we can do the following to achieve this:
1. Scraper provide the the html code editor code
2. There is 4 css files we need to download from FCC so we don't have to style the code editor
```
<link rel="stylesheet" href="/bower_components/CodeMirror/lib/codemirror.css">
<link rel="stylesheet" href="/bower_components/CodeMirror/addon/lint/lint.css">
<link rel="stylesheet" href="/bower_components/CodeMirror/theme/monokai.css">
<link rel="stylesheet" href="/css/ubuntu.css">
```
3. Looks for all text area in the code editor and disable them so teachers can't edit the code (Not very important because we don't really submit the code back to FCC/ save it anywhere)

**Comment by user512** [comment]
We also need to scrape the challenge description.

**Comment by user512** [comment]
After some investigation, found out we don't need to scrape the student solution since it's in the link query string.

For instance, `https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%3B%0A%0AmyStr%20%3D%20%22This%20is%20the%20start.%20%22%20%2B%20%22This%20is%20the%20end.%22%3B%0A%0A%0A`

We simply need to decode the string after `solution=` to get student solutions.
http://meyerweb.com/eric/tools/dencoder/

**Comment by user512** [comment]
After some investigation, found out we don't need to scrape the student solution since it's in the link query string.

For instance, `https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%3B%0A%0AmyStr%20%3D%20%22This%20is%20the%20start.%20%22%20%2B%20%22This%20is%20the%20end.%22%3B%0A%0A%0A`

We simply need to decode the string after `solution=` to get student solutions.
http://meyerweb.com/eric/tools/dencoder/

**Comment by user512** [comment]
Deprecated by https://github.com/user512/teacher_dashboard/issues/16 & https://github.com/user512/teacher_dashboard/issues/17
